server:
  port: 8080

aliyun:
  oss:
    accessKeyId: xxxxxx
    accessKeySecret: xxxxxx
    endpoint: xxxxxx
    bucketName: xxxxxx
    policyExpire: 300
    maxSize: 10
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin
    executor:
      appname: multi-thread
      address:
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      port: 9981
      logretentiondays: 30
spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/personal?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username : root
    password : 1234
  redis:
    host: 192.168.64.9
    port: 6379
    password: ydy@123456
    database: 1
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0