server:
  port: 8081

aliyun:
  oss:
    # API??
    # ?????????????
    accessKeyId: LTAI5tGaf3MA1tJBr5bwo133
    # ????????????oss????????????
    accessKeySecret: 3CThxJo8zSxf7VCpvfn4xIml7rKb89
    # oss????????
    endpoint: oss-cn-shanghai.aliyuncs.com
    # oss?????
    bucketName: example-jiangnan
    # url???(S)
    policyExpire: 300
    # ??????(M)
    maxSize: 10
