server:
  port: 8081

aliyun:
  oss:
    # API??
    # ?????????????
    accessKeyId: xxxxxx
    # ????????????oss????????????
    accessKeySecret: xxxxxx
    # oss????????
    endpoint: xxxxxx
    # oss?????
    bucketName: xxxxxx
    # url???(S)
    policyExpire: 300
    # ??????(M)
    maxSize: 10
